name: Keep Render Backend Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:        # Optional: manually trigger

jobs:
  ping-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Curl Render backend to keep it awake
        run: curl -s https://iems-backend.onrender.com || echo "Ping failed"
